data_ingestion:
  bucket_name: "kaggle-tap30"
  object_name: "tap30-taxi-demands-data.txt"
  storage_path: "s3.ir-thr-at1.arvanstorage.ir"
  train_ratio: 0.9
  artifact_dir: "artifacts"

data_processing:
  shift: 17

model_training:
  n_estimators: 500 # number of trees
  max_samples: 0.9 # If bootstrap is True, the number of samples to draw from X to train each base estimator
  n_jobs: -1 #The number of jobs to run in parallel. -1 means using all processors.
